### ISSUE TITLE
Yeni kaynak ekleme hakkında

### ISSUE THREAD

**Issue by ilker0** [gelis-tr-io/terminoloji#1]
Merhabalar hocam ekleyeceğimiz makale veya yazıyı alıntı adresini göstererek paylaşabilir miyiz ? Yoksa baştan sona kendimizin mi yazması lazım ?

**Comment by hurata** [comment]
Bence tabii ki eklenebilir ama içeriğin kaynağının iyi belirlenmesi gerekebilir. İnternette gördüğün bi makale aldığın websiteye de  ait olmayabilir. 
Ek olarak içeriğin teknik anlamda doğruluğundan emin olabilmek için konu hakkında da biraz yetkinliğin olması gerekir  diğer türlü bu platformda İnternet çöplüğüne karışabilir. 

**Edit**: bu tarz sorular için destek kısmı daha  uygun.

Saygılarımla.

**Comment by tarikguney** [comment]
Selamlar Ilker. Eklenen makalenin asagida ki sartlari saglamasi gerekir:

1. Yazarin izni var mi? Alinti bile gosterilse, yazar izin vermis olmasi lazim. Eger alinti yaparak paylasima genel olarak izin vermisse sorun yok.
2. Tecrubelerinden yola cikarak, makalenin dogrulugundan ve kalitesinden emin misin?
3. Yazar makalesinin gelistr.io toplugunun ortak akli tarafindan degisitirilmesine razi mi?
4. Begendigin bir bakis acisini yakalamis mi?

**Comment by ilker0** [comment]
Teşekkürler Hocam @tarikguney

**Comment by oktaysenkan** [comment]
Repo pinlenirse daha iyi olacağını düşünüyorum. @tarikguney
